### ISSUE TITLE
Merge upstream

### ISSUE THREAD

**Issue by trouch** [FYSETC/Marlin-2.0.x-FYSETC#1]
FYI, I've submitted a PR upstream
https://github.com/MarlinFirmware/Marlin/pull/14407

Good news it compiles, but I can't test it yet.
Would be nice if you could give it a try !

**Comment by GerogeFu** [comment]
I have read the PR, i think it's better to leave this repo  as it is before more people test the firmware. Then i will change the code. And we will have a try the PR .
