### ISSUE TITLE
Error during compiling the firmware

### ISSUE THREAD

**Issue by wester1** [FYSETC/Marlin-2.0.x-FYSETC#16]
Compilation was succesfull but I have 1 yellow remark:
C:\Users\wes.platformio\packages\framework-arduinoststm32-maple\STM32F1\libraries\STM32ADC\src\utility\util_adc.c:10:30: warning: 'adc_result' initialized and declared 'extern'
extern volatile unsigned int adc_result = 0;

Can I ignore it?

**Comment by GerogeFu** [comment]
ignore warning

**Comment by wester1** [comment]
tnx a lot
