### ISSUE TITLE
Wrong DGUS Serial Port configured for F6 Board

### ISSUE THREAD

**Issue by nguidi** [FYSETC/Marlin-2.0.x-FYSETC#17]
### Description

F6 Board DGUS Serial Port is set to 3 instead of 2 in configuration_adv.h (https://github.com/FYSETC/Marlin-2.0.x-FYSETC/tree/F6/2.0.x) cousing the display to become unresponsive.

### Steps to Reproduce

1. Download Branch F6/2.0.X
2. Compile and Upload
3. Connect the FYSTLCD-2.0 into FPC Socket using the FPC Cable.

**Expected behavior:** The Display is responsive

**Actual behavior:** The display get stuck on FYSETC logo.

#### Fix

Change DGUS Serial Port configured in `Configuration_adv.h` from `#define DGUS_SERIAL_PORT 3` to `#define DGUS_SERIAL_PORT 2`

**Comment by GerogeFu** [comment]
Really thanks for this info , i already update it.
