### ISSUE TITLE
AIO II temperature sensors not working

### ISSUE THREAD

**Issue by gouache** [FYSETC/Marlin-2.0.x-FYSETC#3]
### Description
TB / TE not working

### Steps to Reproduce

1. M105
2. always returnn same value
 ok T:-15.00 /0.00 B:-15.00 /0.00 @:0 B@:0

**Expected behavior:** get normal temperature

**Actual behavior:** abnormal temperature

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by GerogeFu** [comment]
Hardware issue , fix or change to another board to test
