### ISSUE TITLE
lib_ldf_mode error

### ISSUE THREAD

**Issue by konqiDAM** [FYSETC/Marlin-2.0.x-FYSETC#4]
### Description

Error: Invalid value: invalid choice: 1. (choose from off, chain, deep, chain+, deep+) for option `lib_ldf_mode` in section [env:fysetc_STM32F1]

### Steps to Reproduce

Just try to compile the code

**Expected behavior:**
Compiles

**Actual behavior:** [What actually happens]
Gives error in line 299

#### Additional Information
I think the line "lib_ldf_mode" should be comented or set to "chain" and not to 1

**Comment by sl1pkn07** [comment]
fixed in upstream with https://github.com/MarlinFirmware/Marlin/commit/4a5f135c5d7493f42a1876552c0fccf068d62b9c
