### ISSUE TITLE
Layer fan only turn on when I click on LCD

### ISSUE THREAD

**Issue by Eliotht** [FYSETC/Marlin-2.0.x-FYSETC#7]
I've installed Cheetah on Ender 3 and everything is fine but the layer fan don't turn on automatically. Even if I configure Slicer for turn on fan on layer 2, I have to do a simple CLICK on the rotary of LCD for turn on the layer fan.. How can we solve it?

Thanks

**Comment by konqiDAM** [comment]
This needs more attention, myself and several more people are having this exact issue, also turning off the fan or any speed change requires a click

**Comment by Eliotht** [comment]
I hope they read us because it's a whore

**Comment by trouch** [comment]
I've noticed that issue with main Marlin code. Doesn't seems to be specific to FYSETC branch. I'll do some SWD debug eventually.

**Comment by trouch** [comment]
Also fan works properly using latest FYSETC build. No LCD click required.

**Comment by trouch** [comment]
As a workaround until proper fix, do not enable SPEAKER in your configuration.
There is a conflict between the fan PWM output and buzzer one.

**Comment by joewys** [comment]
on every change of layer there is a lcd click whit the new firmware :/
