### ISSUE TITLE
warning: no 5v usb jumper

### ISSUE THREAD

**Issue by raffosan** [FYSETC/Marlin-2.0.x-FYSETC#8]
the board has  no 5v jumper on the usb, so when the printer is shout off will continue to gain power from any usab device connected, in my cvase raspberry pi , making also the fan spinning, this has a big risk factor for the usb ampere limits.

planning to use the usb  second pinout to avoid problems.

**Comment by trouch** [comment]
I'm using a USB Hub witch individual power switch to avoid such case, no matter of the board. 
It also protect your host CPU for short on the sig lines.
https://www.amazon.com/Sabrent-4-Port-Individual-Switches-HB-UMLS/dp/B00BWF5U0M/ref=sr_1_2_sspa

You can also add a small paper on your USB connector power pin as a free workaround.
