### ISSUE TITLE
Build fails during fysetc_STM32F1.py

### ISSUE THREAD

**Issue by wees** [FYSETC/Marlin-2.0.x-FYSETC#9]
### Description

Running build in PlatformIO fails 

### Steps to Reproduce

1. git clone latest version of Marlin-2.0.x-FYSETC
2. Open in PlatformIO (I'm using OS X VsCode, but it fails in Atom as well) 
3. Without changing any configuration, click Build.
4. Build fails.

**Expected behavior:** Build is successful

**Actual behavior:** Build Fails

#### Additional Information
The Build is failing in buildroot/share/PlatformIO/scripts/fysetc_STM32F1.py If I comment out: 
`extra_scripts = buildroot/share/PlatformIO/scripts/fysetc_STM32F1.py` in platformio.ini, the build is successful.

It's almost as if the function is outputting the help documentation instead of running correctly.

First part of the console:
![image](https://user-images.githubusercontent.com/5941753/61585954-17540500-ab26-11e9-9927-aecc7555794a.png)

Console Continued:
![image](https://user-images.githubusercontent.com/5941753/61586016-79613a00-ab27-11e9-854c-a1d8799639e2.png)

**Comment by GerogeFu** [comment]
I don't have MAC to test that. I seems to be the permission issue. In windows you can use admin to run vscode.

**Comment by GerogeFu** [comment]
Refer to this 
https://forum.fysetc.com/d/67-firmware-compile-error/34
